modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="solarcooker"
    version="${file.jarVersion}"
    displayName="Solar Cooker"
    displayURL="https://github.com/cech12/SolarCooker"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Solar Cooker.
    '''
[[dependencies.solarcooker]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solarcooker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solarcooker]]
   modId="jei"
   mandatory=false
   versionRange="[8.0.0.12,)"
   ordering="NONE"
   side="BOTH"