modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/cech12/BrickShears/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="solarcooker"
    version="${file.jarVersion}"
    displayName="Solar Cooker"
    displayURL="https://github.com/cech12/SolarCooker"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Solar Cooker.
    '''
[[dependencies.solarcooker]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.7,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solarcooker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solarcooker]]
   modId="jei"
   mandatory=false
   versionRange="[9.7.0.192,)"
   ordering="NONE"
   side="BOTH"